parent: ZOneTheme
name: PepitesDuTerroir
display_name: Le thème des pépites du terroir
version: 1.0.0
author:
  name: "Guillaume Sainthillier"
  url: "https://silarhi.fr"
assets:
  use_parent_assets: false
